# Generated by Django 3.1.2 on 2021-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opinion_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=('male', 'male'), max_length=255)),
                ('state', models.CharField(choices=[('Niger', 'Niger')], default=('Niger', 'Niger'), max_length=255)),
                ('LGA', models.CharField(choices=[('Chanchaga', 'Chanchaga')], default=('Chanchaga', 'Chanchaga'), max_length=255)),
                ('ward', models.CharField(choices=[('Tudun Wada South', 'Tudun Wada South'), ('Tudun Wada North', 'Tudun Wada North'), ('Minna South', 'Minna South'), ('Minna Central', 'Minna Central'), ('Limawa A', 'Limawa A'), ('Limawa B', 'Limawa B'), ('Sabon Gari', 'Sabon Gari'), ('Nasarawa A', 'Nasarawa A'), ('Nasarawa B', 'Nasarawa B'), ('Nasarawa C', 'Nasarawa C')], default=('Limawa A', 'Limawa A'), max_length=255)),
                ('phone_number', models.IntegerField()),
                ('programming_language', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PYTHON', 'PYTHON')], default=('JAVASCRIPT', 'JAVASCRIPT'), max_length=255)),
            ],
        ),
    ]
