# Generated by Django 3.1.2 on 2021-01-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opinion_form',
            new_name='opinion',
        ),
    ]
