# Generated by Django 3.1.2 on 2021-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_auto_20210103_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='ward',
            field=models.CharField(choices=[('Tudun Wada South', 'Tudun Wada South'), ('Tudun Wada North', 'Tudun Wada North'), ('Minna South', 'Minna South'), ('Makera', 'Makera'), ('Minna Central', 'Minna Central'), ('Limawa A', 'Limawa A'), ('Limawa B', 'Limawa B'), ('Sabon Gari', 'Sabon Gari'), ('Nasarawa A', 'Nasarawa A'), ('Nasarawa B', 'Nasarawa B'), ('Nasarawa C', 'Nasarawa C')], default=('Limawa A', 'Limawa A'), max_length=255),
        ),
    ]
