# Generated by Django 3.1.2 on 2021-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0003_auto_20210106_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
